### PR TITLE
Updated to be compatible with CBO Unofficial

### PR DESCRIPTION
**Pull request by csirke128**
Changed the genes to be based on CBO genes, so it would not need compatibility patch for each overhaul mod. The clothing can be selected from the CBO clothing categories in the barbershop.

### CODE REVIEW

**Comment by csirke128** [comment]
Load order:
Lazy's Skimpy Accessories
[any mod that modifies gene files]
CBO Unofficial
Lazy's Skimpy Accessories CBO Compatibility

**Comment by PerplexedPeach** [comment]
Hi thanks for the contribution! There's currently no stable version of CBO to target - do you know if all the CBO versions have a stable set of genes?

**Comment by csirke128** [comment]
Hi, CBO Unofficial is working for 1.13.x currently, and there likely won't be any changes that would affect this patch that much.
If there are changes, I can raise a pull request again to fix those. (like I might change some of the legwear for CBO, but it might not happen any time soon)
Also not sure if Mange would come back and update CBO, but since last update was in January, its hard to tell.

**Comment by PerplexedPeach** [comment]
I see, I just downloaded the unofficial CBO so will be trying that out and this compatibility patch

**Comment by PerplexedPeach** [comment]
image
The skimpy affairs clothes works fine, but the base CBO clothes don't seem to work (the localization for the clothing items also seem to be missing).  Are there additional mods I need for the unofficial CBO? If I turn off the cbo_compatibility mod then those genes don't even exist.

No clothes seems to be missing from clothes, but this may be due to something else? Note that turning on "Naked" will change shape keys and make some of the clothing items clip.

**Comment by csirke128** [comment]
Hi, I think I only have localization for English, at "CBO Unofficial\localization\english\CBO_CS_l_english.yml"
I think even with this, there might be some localization issues for CBO, I didnt have time fix everything for 1.13.x (I'll update the mod again, but currently working on adding cbo animation pack to it)
The mod is standalone, so you should have a load order like pasted above:
(so dont need CBO 1.8.4, or CBO CS or CBO Unofficial fix, now its all just CBO Unofficial)
https://www.loverslab.com/topic/229678-mod-cbo-unofficial/

Lazy's Skimpy Accessories
[any mod that modifies gene files]
CBO Unofficial
Lazy's Skimpy Accessories CBO Compatibility

Which item is clipping? Maybe will need to add 
	entity = { required_tags = "undressed"		shared_pose_entity = torso }
to all accessories, if they are clipping at naked.

**Comment by PerplexedPeach** [comment]
I am using English, so it should localize. My load order is below for testing with CBO and skimpy accessories:
image

These options under Revealing Plunge Dress don't seem to do anything
image


Missing naked/no clothes option in clothes, forcing Naked toggle to actually be naked
image

All accessories seem to clip when Naked is toggled on
image

vs equipping via clothes
image

**Comment by csirke128** [comment]
Hi, weird, it shows CBO as 2.2GB for you, it should be 4GB
Could it be you are missing some files for CBO?

**Comment by PerplexedPeach** [comment]
Ah you're right, there was issue with the extraction! I think everything works now so I'll merge this.

**Pull request merged**
