### PR TITLE
Compatibility with 1.14.x

### PR DESCRIPTION
**Pull request by csirke128**
Added the accessories to CBO Unofficial 1.5, so only need to trigger the accessories by setting lida_active to true This should make it so that there is no dependency on the CBO gene files

### CODE REVIEW

**Comment by PerplexedPeach** [comment]
Hi, thanks for the contribution. This PR seems to remove all the CBO definitions from the compatibility mod - are you saying that the descriptions for those accessories are now in the CBO unofficial mod instead? I think that's fine, but it'll also mean that you will need to add item descriptions if/when I add more accessory assets. e.g. whenever I add a new clothing piece, adding it to CBO Unofficial will be on you instead of me. Is that all right?

**Comment by csirke128** [comment]
Hi, Yea I added the genes into CBO itself, the main Issue i had is that CBO Unofficial Base and CBO Unofficial Mesh would have different clothing in the CBO genes, so either I made it so that the genes are added by CBO, or there would need to be different patches for CBO Base and CBO Mesh. So seems simpler to just include the patch, and makes it possible to add other things to those CBO genes as well. 
The idea is from AGOT Submodule core, where its using similar ways of doing compatibility, that the mods have a flag that is set when they are added, and based on that flag the clothing are added to the custom clothing that can be selected.

Yea, I can add the new genes from new clothing to CBO when those are added to the main mod.

**Comment by PerplexedPeach** [comment]
Got it, mb forgot to merge this request

**Comment by PerplexedPeach** [comment]
I currently am in between moving so don't have access to my PC for uploading to LL

**Pull request merged**
